[project]
name = 'TimeBank'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.service-exchange]
path = 'contracts/service-exchange.clar'
clarity_version = 2
epoch = 2.5

[contracts.time-credit]
path = 'contracts/time-credit.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
